### ISSUE TITLE
Better game win and over screen.

### ISSUE THREAD

**Issue by momozor** [momozor/blue-beanie#1]
Current issues
---

1. Text aligning is horrible. The each level game over instruction text is missing.
2. Ugly format/fonts.
3. Background is plain opaque color.

Suggested improvements
---

1. Adjust text aligning for every single game over and game win screens.
2. Use attractive bitmap font for the texts.
3. Replace background plain color with images or a preview for the playing level.

**Comment by prattheev** [comment]
@faraco I could take this. But before I have some doubts.

**Comment by faraco** [comment]
Hi, welcome and thank you for coming to the project! :smile: 

Do you need any help on where to begin?

**Comment by momozor** [comment]
very old. deprecating this issue.
